spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: "jdbc:h2:mem:test"
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect